<a href="https://colab.research.google.com/github/piyushsinhrajput/ML-7218-6D/blob/main/P4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv("/content/01 covid_toy (2).csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [7]:
print(df.cough.value_counts())

print()
print()

print(df.city.value_counts())

cough
Mild      62
Strong    38
Name: count, dtype: int64


city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [8]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [10]:
x=df.iloc[:,0:5]
y=df.drop(x,axis='columns')

print(x.head())

print()
print()
print()

print(y.head())

   age  gender  fever cough     city
0   60    Male  103.0  Mild  Kolkata
1   27    Male  100.0  Mild    Delhi
2   42    Male  101.0  Mild    Delhi
3   31  Female   98.0  Mild  Kolkata
4   65  Female  101.0  Mild   Mumbai



  has_covid
0        No
1       Yes
2        No
3        No
4        No

In [13]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
print(x_train.head())
print()
print()
print(y_train.head())

    age  gender  fever   cough       city
79   48  Female  103.0    Mild    Kolkata
96   51  Female  101.0  Strong    Kolkata
62   56  Female  104.0  Strong  Bangalore
2    42    Male  101.0    Mild      Delhi
9    64  Female  101.0    Mild      Delhi


   has_covid
79       Yes
96       Yes
62       Yes
2         No
9         No

In [15]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

In [16]:
si=SimpleImputer()
le=LabelEncoder()

In [23]:
y_train.has_covid = le.fit_transform(y_train.has_covid)
y_test.has_covid = le.fit_transform(y_test['has_covid'])

In [24]:
x_train['fever'] = si.fit_transform(x_train[['fever']])

In [25]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()
x_train_cough = oe.fit_transform(x_train[['cough']])
x_test_cough = oe.fit_transform(x_test[['cough']])

In [29]:
from sklearn.preprocessing import OneHotEncoder

In [30]:
ohe = OneHotEncoder(drop = 'first',sparse_output = False)

In [33]:
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])
x_test_gender_city = ohe.transform(x_test[['gender','city']])

print(x_train_gender_city.shape)
print(x_test_gender_city.shape)

(80, 4)
(20, 4)

In [34]:
transformer = [('trans1',SimpleImputer(),['fever']),
               ('trans2',OrdinalEncoder(categories = [['Mild','Strong']]),['cough']),
               ('trans3',OneHotEncoder(sparse_output = False,drop = 'first'),['gender','city'])]

In [38]:
from sklearn.compose import ColumnTransformer

ct = ColumnTransformer(transformers = transformer,remainder = 'passthrough').set_output(transform = 'pandas')

In [39]:
x_train_transformed = ct.fit_transform(x_train)

In [42]:
x_train_trans = ct.fit_transform(x_train)

In [43]:
x_train_trans.sample(5)

,trans1__fever,trans2__cough,trans3__gender_Male,trans3__city_Delhi,trans3__city_Kolkata,trans3__city_Mumbai,remainder__age
28,104.000000,0.0,1.0,0.0,1.0,0.0,16
57,99.000000,1.0,0.0,0.0,0.0,0.0,49
90,99.000000,1.0,0.0,1.0,0.0,0.0,59
25,100.783784,0.0,1.0,0.0,0.0,1.0,23
26,100.000000,0.0,0.0,0.0,1.0,0.0,19

In [45]:
X_test_trans=ct.transform(x_test)

In [46]:
x_train_trans.shape

(80, 7)

In [49]:
print(x_train_trans.sample(5))
print()
print()
print(X_test_trans.shape)

    trans1__fever  trans2__cough  trans3__gender_Male  trans3__city_Delhi  \
84           98.0            1.0                  0.0                 0.0
31          103.0            0.0                  1.0                 0.0
18           98.0            0.0                  0.0                 0.0
20           98.0            1.0                  1.0                 0.0
52          100.0            1.0                  0.0                 0.0

    trans3__city_Kolkata  trans3__city_Mumbai  remainder__age
84                   0.0                  1.0              69
31                   1.0                  0.0              83
18                   0.0                  0.0              64
20                   0.0                  0.0              12
52                   0.0                  0.0              47


(20, 7)